title: 我的博客
description: 这是我的博客网站。
theme: minima
baseurl: "/-.github.io" # 确保与仓库名一致
url: "https://masterlyj.github.io"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html # 博客文章的链接格式
